# Generated by Django 4.2.2 on 2023-06-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('module_code', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=50)),
            ],
        ),
    ]
