# Generated by Django 4.2.2 on 2023-06-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0002_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nielit.c_intro'),
        ),
    ]
