# Generated by Django 4.2.2 on 2023-06-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0003_alter_syllabus_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='syllabus',
            new_name='Module',
        ),
    ]
