# Generated by Django 4.2.2 on 2023-06-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0004_rename_syllabus_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_detail', models.CharField(max_length=500)),
                ('extra_md', models.CharField(max_length=500, null=True)),
                ('chapter_name', models.CharField(max_length=100)),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nielit.module')),
            ],
        ),
    ]
