# Generated by Django 4.2.2 on 2023-06-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0005_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='extra_md',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='module_detail',
        ),
    ]
