# Generated by Django 4.2.2 on 2023-06-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0007_module_extra_md_module_module_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='extra_md',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
