# Generated by Django 4.2.2 on 2023-06-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nielit', '0008_alter_module_extra_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
