# Generated by Django 4.2.2 on 2023-07-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=50)),
                ('partner_details', models.TextField()),
                ('partner_social_media_link', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
