# Generated by Django 4.2.2 on 2023-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(default=None, max_length=10, null=True, upload_to='partner_logo'),
        ),
    ]
