# Generated by Django 4.2.2 on 2023-07-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_partner_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_logo',
            field=models.ImageField(default=None, max_length=50, null=True, upload_to='partner_logo/'),
        ),
    ]
